name: Build & Deploy

on:
  # push:
  #   branches: [ master ]

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.3

    - name: Install&Init Fun
      env:
        URL: ${{ secrets.TEMPLATE_URL }}
        REGION: ${{ secrets.REGION }}
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
      run: |
        npm install @alicloud/fun -g
        fun --version

        curl $URL -o template.yml
        echo -e "ACCOUNT_ID=${ACCOUNT_ID}\nREGION=${REGION}\nACCESS_KEY_ID=${ACCESS_KEY_ID}\nACCESS_KEY_SECRET=${ACCESS_KEY_SECRET}\nTIMEOUT=60\nRETRIES=3" >> .env

    - name: Build FC
      run: |
        chmod +x bootstrap
        fun build
    - name: Deploy
      run: |
        fun deploy -y
